version: '3.1'
services:
  mysql-m:
    image: mysql:8.0
    container_name: mysql-m
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    volumes:
      - ./mysql/master:/var/lib/mysql
      - ./master-my.cnf:/etc/mysql/conf.d/master-my.cnf
    ports:
      - "3306:3306"

  mysql-s1:
    image: mysql:8.0
    container_name: mysql-s1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    volumes:
      - ./mysql/slave1:/var/lib/mysql
      - ./slave-my.cnf:/etc/mysql/conf.d/slave-my.cnf
    ports:
      - "3307:3306"

  mysql-s2:
    image: mysql:8.0
    container_name: mysql-s2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    volumes:
      - ./mysql/slave2:/var/lib/mysql
      - ./slave-my.cnf:/etc/mysql/conf.d/slave-my.cnf
    ports:
      - "3308:3306"
